import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import axios from 'axios'
import { useState, useEffect } from 'react'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [channels, setChannels] = useState([])

  useEffect(() => {
    axios.get('/api/channels').then((res) => {
      setChannels(res.data)
    })
  }, [])

  const deleteChannel = async (id) => {
    axios.delete(`/api/channels/${id}`).then((res) => {
      setChannels(channels.filter((channel) => channel.id !== id))
    })
  }

  const editChannel = async (id) => {
    axios.put(`/api/channels/${id}`).then((res) => {
      setChannels(channels.filter((channel) => channel.id !== id))
    })
  }


  const postChannel = async (id) => {
    axios.post(`/api/channels/${id}`).then((res) => {
      setChannels(channels.filter((channel) => channel.id !== id))
    })
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <h1>Discord Clone</h1>
        </div>
        <div>
          <h1>Create a channel</h1>
        </div>
        <div>
          <form
            onSubmit={(e) => {
              e.preventDefault()
              const name = e.target.name.value
              postChannel(name)
            }}
          >
            <input type="text" name="name" />
            <button type="submit">Create</button>
          </form>
        </div>
        <div className={styles.grid}>
        {channels.map((channel) => {
          return (
            <div key={channel.id}>
              <Link href={`/channels/${channel.id}`}>
              <h1>{channel.name}</h1>
              <p>{channel.created}</p>
              {/* <button onClick={deleteChannel(channel.id)}>Delete</button> */}
              {/* <button onClick={editChannel(channel.id)}>Edit</button> */}
            </Link>
            </div>
          )
        })}
        </div>
      </main>
    </>
  )
}
